"""Deterministic MCP Server Generator & Reproducible Exporter (T09 & T12).

Consumes an immutable `ApiContract`, `ToolPlan`, and `RuntimePolicy` to emit a
standalone, self-contained MCP server package and reproducible `.zip` bundle.

Security & Determinism Invariants:
- Templates never invoke local or cloud LLMs or make network calls.
- Untrusted strings (operation names, descriptions, paths, parameter names/schemas)
  are NEVER interpolated into Python source code; they are stored in `contract.json`,
  `tool_plan.json`, and `policy.json` and loaded via `json.loads` at runtime.
- Every generated `.py` file is validated via `ast.parse()` before writing.
- Identical frozen inputs produce byte-for-byte identical files, `manifest_hash`,
  and `.zip` SHA-256 digests (`FR-13`).
"""

from __future__ import annotations

import ast
import json
import re
import zipfile
from pathlib import Path
from typing import Any

from packages.core.contracts import (
    ApiContract,
    GenerationManifest,
    ToolPlan,
    canonical_json_bytes,
    sha256_hex,
)
from packages.core.planning import RuntimePolicy
from packages.core.readiness import check_contract_freeze_readiness
from packages.core.support_registry import get_capability_matrix_dict
from packages.runtime.engine import env_var_for_scheme, env_var_for_server

GENERATOR_VERSION = "0.2.0"
RUNTIME_VERSION = "0.2.0"
MCP_SDK_PIN = "2.3.0"
HTTPX_PIN = "0.28.1"
JSONSCHEMA_PIN = "4.26.0"
PYDANTIC_PIN = "2.14.0"

FIXED_ZIP_DATETIME = (2026, 1, 1, 0, 0, 0)


def sanitize_package_slug(raw_slug: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_]+", "_", raw_slug.strip()).strip("_").lower()
    if not slug or not slug[0].isalpha():
        slug = f"spigot_{slug}" if slug else "spigot_generated_server"
    return slug


def _write_lf_text(path: Path, content: str) -> bytes:
    normalized = content.replace("\r\n", "\n").replace("\r", "\n")
    if not normalized.endswith("\n"):
        normalized += "\n"
    data = normalized.encode("utf-8")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return data


def _write_canonical_json(path: Path, payload: Any) -> bytes:
    formatted = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False)
    return _write_lf_text(path, formatted)


def _render_server_py(package_slug: str, server_name: str) -> str:
    # Only safe verified identifiers/literals are placed in Python source;
    # all contract/tool descriptions and paths are loaded from JSON files.
    safe_server_name = (
        re.sub(r"[^a-zA-Z0-9_-]+", "-", server_name).strip("-") or "spigot-mcp-server"
    )
    code = f'''"""Standalone MCP stdio server generated by Spigot (DocForge MCP).

This entrypoint loads inert JSON artifacts (`contract.json`, `tool_plan.json`,
`policy.json`) from the package root and delegates execution to the bundled
`runtime_engine` without requiring the Spigot compiler backend or SQLite DB.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from {package_slug}.runtime_engine import load_engine_from_package_dir

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
SERVER_NAME = {json.dumps(safe_server_name)}
SERVER_VERSION = {json.dumps(RUNTIME_VERSION)}


def create_engine():
    return load_engine_from_package_dir(
        PACKAGE_ROOT,
        server_name=SERVER_NAME,
        server_version=SERVER_VERSION,
    )


def main() -> None:
    engine = create_engine()
    asyncio.run(engine.run_stdio())


if __name__ == "__main__":
    main()
'''
    ast.parse(code, filename=f"{package_slug}/server.py")
    return code


def _render_smoke_test_py(package_slug: str) -> str:
    code = f'''"""Generated offline smoke tests for {package_slug} (Spigot / DocForge MCP)."""

from __future__ import annotations

import asyncio

from {package_slug}.server import create_engine


def test_engine_loads_and_lists_enabled_tools() -> None:
    engine = create_engine()
    tools = engine.list_tools_sync()
    assert len(tools) == len(engine.enabled_tool_names)
    for tool in tools:
        assert tool.name
        assert isinstance(tool.inputSchema, dict)


def test_unknown_tool_is_rejected_without_network() -> None:
    engine = create_engine()
    res = asyncio.run(engine.call_tool_async("__nonexistent_tool__", {{}}))
    assert res.is_error is True
    assert "POLICY_DENIED" in res.content[0].text
'''
    ast.parse(code, filename="tests/test_smoke.py")
    return code


def _render_env_example(contract: ApiContract) -> str:
    lines = [
        "# Spigot (DocForge MCP) Generated Server Runtime Environment Variables",
        "# Populate secret values in your local environment before running.",
        "# NEVER commit actual credentials to version control.",
        "",
    ]
    for srv in sorted(contract.servers, key=lambda s: s.server_id):
        env_name = env_var_for_server(srv.server_id)
        lines.append(
            f"# Override base URL for server '{srv.server_id}' (default: {srv.base_url})"
        )
        lines.append(f"{env_name}=")
    for scheme in sorted(contract.security_schemes, key=lambda s: s.scheme_id):
        env_name = env_var_for_scheme(scheme.scheme_id)
        lines.append(
            f"# Credential for security scheme '{scheme.scheme_id}' (type: {scheme.type})"
        )
        lines.append(f"{env_name}=")
    lines.extend(
        [
            "",
            "# Action Approval Authority (required when policy mode is 'approval_required')",
            "# Shared HMAC secret (>=16 chars) or workspace key file provisioned by Spigot Local API",
            "SPIGOT_APPROVAL_SECRET=",
            "SPIGOT_APPROVAL_SECRET_FILE=.spigot/workspace/approval_authority.key",
            "# Persistent SQLite ledger path for atomic single-use nonce replay protection",
            "SPIGOT_APPROVAL_LEDGER_PATH=.spigot/consumed_approvals.sqlite3",
            "# Per-invocation single-use owner approval token JSON (when executing an approved write)",
            "SPIGOT_ACTION_APPROVAL_TOKEN=",
        ]
    )
    return "\n".join(lines) + "\n"


def _render_pyproject_toml(package_slug: str) -> str:
    return f"""[project]
name = "{package_slug}"
version = "{RUNTIME_VERSION}"
description = "Standalone MCP server package generated by Spigot (DocForge MCP)"
readme = "README.md"
requires-python = ">=3.12"
license = {{ text = "Apache-2.0" }}
dependencies = [
    "mcp=={MCP_SDK_PIN}",
    "httpx=={HTTPX_PIN}",
    "jsonschema=={JSONSCHEMA_PIN}",
    "pydantic=={PYDANTIC_PIN}",
]

[project.scripts]
{package_slug} = "{package_slug}.server:main"
"""


def _render_readme_md(
    contract: ApiContract,
    tool_plan: ToolPlan,
    policy: RuntimePolicy,
    package_slug: str,
) -> str:
    tool_bullets = []
    for op_id in tool_plan.operation_ids:
        t_name = tool_plan.tool_names[op_id]
        t_desc = tool_plan.descriptions.get(op_id, "")
        clean_desc = " ".join(t_desc.splitlines()).strip()
        tool_bullets.append(f"- `{t_name}` (`{op_id}`): {clean_desc}")
    tools_section = "\n".join(tool_bullets) if tool_bullets else "- *(No enabled tools)*"

    return f"""# {contract.id} — Generated MCP Server (`{package_slug}`)

Generated deterministically by **Spigot (DocForge MCP)** (`v{GENERATOR_VERSION}`).

- **Contract ID:** `{contract.id}` (Revision `{contract.revision}`)
- **Contract Canonical SHA-256:** `{contract.canonical_hash}`
- **Tool Plan SHA-256:** `{tool_plan.plan_hash}`
- **Policy Mode:** `{policy.mode}`
- **Network Profile:** `{policy.network_profile}`

## Standalone Execution

This package runs independently of the **Spigot / DocForge MCP** compiler backend,
SQLite database, and local LLM runtime.

1. Copy `.env.example` to `.env` or export the listed environment variables.
2. Run the MCP stdio server:

```bash
python -m {package_slug}.server
```

## Advertised MCP Tools

{tools_section}

## Security & Provenance Notice

- All tool descriptions, paths, and JSON schemas are loaded as inert JSON data from
  `contract.json`, `tool_plan.json`, and `policy.json`.
- Runtime policy enforcement (`{policy.mode}`) and network egress guards
  (`{policy.network_profile}`) execute before any HTTP request is dispatched.
- Credentials resolved from `SPIGOT_CRED_*` environment variables are automatically
  scrubbed from `stderr` traces and structured error envelopes.
"""


def _render_license() -> str:
    return """Apache License 2.0 — Spigot (DocForge MCP) Redistributable Runtime

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
"""


def _build_compatibility_report(
    contract: ApiContract,
    tool_plan: ToolPlan,
    policy: RuntimePolicy,
) -> dict[str, Any]:
    enabled_set = set(tool_plan.operation_ids)
    disabled_ops = [
        {
            "operation_id": op.stable_id,
            "http_method": op.method,
            "relative_path": op.relative_path,
            "semantic_effect": op.semantic_effect,
            "support_status": op.support_status,
            "reason": (
                "blocked_in_contract"
                if op.support_status != "supported"
                else f"excluded_by_plan_or_policy_{policy.mode}"
            ),
        }
        for op in sorted(contract.operations, key=lambda o: o.stable_id)
        if op.stable_id not in enabled_set
    ]
    return {
        "schema_version": "1.0",
        "generator_brand": "Spigot (DocForge MCP)",
        "generator_version": GENERATOR_VERSION,
        "runtime_version": RUNTIME_VERSION,
        "mcp_sdk_version": MCP_SDK_PIN,
        "contract_hash": contract.canonical_hash,
        "plan_hash": tool_plan.plan_hash,
        "policy_hash": policy.compute_policy_hash(),
        "enabled_operation_ids": list(tool_plan.operation_ids),
        "disabled_operations": disabled_ops,
        "capability_matrix": get_capability_matrix_dict(),
    }


def generate_server_package(
    contract: ApiContract,
    tool_plan: ToolPlan,
    policy: RuntimePolicy,
    output_dir: Path,
    *,
    package_slug: str = "spigot_generated_server",
    manifest_id: str | None = None,
    require_freeze_ready: bool = True,
) -> GenerationManifest:
    """Generate a deterministic, standalone MCP server package on disk."""
    if require_freeze_ready:
        ready, blockers = check_contract_freeze_readiness(
            contract, selected_operation_ids=tool_plan.operation_ids
        )
        if not ready:
            codes = ", ".join(f"{b.code}({b.affected_field})" for b in blockers)
            raise ValueError(f"Contract '{contract.id}' is not freeze-ready: {codes}")

    if contract.canonical_hash != tool_plan.contract_hash:
        raise ValueError(
            f"ToolPlan contract_hash ({tool_plan.contract_hash}) does not match "
            f"ApiContract canonical_hash ({contract.canonical_hash})"
        )

    expected_policy_hash = policy.compute_policy_hash()
    if expected_policy_hash != tool_plan.policy_hash:
        raise ValueError(
            f"ToolPlan policy_hash ({tool_plan.policy_hash}) does not match "
            f"RuntimePolicy hash ({expected_policy_hash})"
        )

    safe_slug = sanitize_package_slug(package_slug)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Read runtime engine source and validate AST
    engine_source_path = Path(__file__).resolve().parent.parent / "runtime" / "engine.py"
    engine_source = engine_source_path.read_text(encoding="utf-8")
    ast.parse(engine_source, filename=f"{safe_slug}/runtime_engine.py")

    contract_dict = contract.model_dump(mode="json", by_alias=True)
    artifact_hashes: dict[str, str] = {}

    def _record_file(rel_path: str, raw_bytes: bytes) -> None:
        artifact_hashes[rel_path] = sha256_hex(raw_bytes)

    # 1. Write inert JSON data files
    _record_file(
        "contract.json",
        _write_canonical_json(output_dir / "contract.json", contract_dict),
    )
    _record_file(
        "tool_plan.json",
        _write_canonical_json(
            output_dir / "tool_plan.json", tool_plan.model_dump(mode="json")
        ),
    )
    _record_file(
        "policy.json",
        _write_canonical_json(output_dir / "policy.json", policy.model_dump(mode="json")),
    )
    _record_file(
        "compatibility_report.json",
        _write_canonical_json(
            output_dir / "compatibility_report.json",
            _build_compatibility_report(contract, tool_plan, policy),
        ),
    )

    # 2. Write configuration, docs, and metadata
    _record_file(
        ".env.example",
        _write_lf_text(output_dir / ".env.example", _render_env_example(contract)),
    )
    _record_file(
        "pyproject.toml",
        _write_lf_text(output_dir / "pyproject.toml", _render_pyproject_toml(safe_slug)),
    )
    _record_file(
        "README.md",
        _write_lf_text(
            output_dir / "README.md",
            _render_readme_md(contract, tool_plan, policy, safe_slug),
        ),
    )
    _record_file(
        "LICENSE",
        _write_lf_text(output_dir / "LICENSE", _render_license()),
    )

    # 3. Write Python package modules (AST-verified)
    init_code = '"""Generated standalone MCP server package."""\n'
    ast.parse(init_code, filename=f"{safe_slug}/__init__.py")
    _record_file(
        f"{safe_slug}/__init__.py",
        _write_lf_text(output_dir / safe_slug / "__init__.py", init_code),
    )
    _record_file(
        f"{safe_slug}/runtime_engine.py",
        _write_lf_text(output_dir / safe_slug / "runtime_engine.py", engine_source),
    )
    server_code = _render_server_py(safe_slug, contract.id)
    _record_file(
        f"{safe_slug}/server.py",
        _write_lf_text(output_dir / safe_slug / "server.py", server_code),
    )

    # 4. Write smoke tests (AST-verified)
    smoke_code = _render_smoke_test_py(safe_slug)
    _record_file(
        "tests/test_smoke.py",
        _write_lf_text(output_dir / "tests" / "test_smoke.py", smoke_code),
    )

    # Compute deterministic template and dependency lock hashes
    generator_self_bytes = Path(__file__).resolve().read_bytes().replace(b"\r\n", b"\n")
    engine_bytes = engine_source.replace("\r\n", "\n").encode("utf-8")
    template_hash = sha256_hex(generator_self_bytes + b"\n---\n" + engine_bytes)

    dep_lock_payload = {
        "mcp": MCP_SDK_PIN,
        "httpx": HTTPX_PIN,
        "jsonschema": JSONSCHEMA_PIN,
        "pydantic": PYDANTIC_PIN,
    }
    dependency_lock_hash = sha256_hex(canonical_json_bytes(dep_lock_payload))

    sorted_artifact_hashes = dict(sorted(artifact_hashes.items()))
    effective_manifest_id = manifest_id or f"manifest-{contract.id}-r{contract.revision}"

    manifest = GenerationManifest(
        id=effective_manifest_id,
        artifact_hashes=sorted_artifact_hashes,
        contract_hash=contract.canonical_hash,
        plan_hash=tool_plan.plan_hash,
        generator_version=GENERATOR_VERSION,
        template_hash=template_hash,
        runtime_version=RUNTIME_VERSION,
        dependency_lock_hash=dependency_lock_hash,
    )
    _write_canonical_json(output_dir / "manifest.json", manifest.model_dump(mode="json"))

    # Remove any unmanifested stale files from output_dir
    expected_rel_paths = set(sorted_artifact_hashes.keys()) | {"manifest.json"}
    for existing_file in list(output_dir.rglob("*")):
        if existing_file.is_file():
            rel_posix = existing_file.relative_to(output_dir).as_posix()
            if rel_posix not in expected_rel_paths:
                existing_file.unlink()

    return manifest


def export_reproducible_zip(package_dir: Path, zip_path: Path) -> bytes:
    """Create a byte-for-byte reproducible `.zip` archive from a generated package directory.

    If `manifest.json` is present in `package_dir`, strictly enforces that only manifested
    files (plus `manifest.json`) exist in `package_dir` and that every file matches its
    manifested SHA-256 digest before archiving.
    """
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    all_files = sorted(
        (p for p in package_dir.rglob("*") if p.is_file()),
        key=lambda p: p.relative_to(package_dir).as_posix(),
    )

    manifest_file = package_dir / "manifest.json"
    if manifest_file.exists():
        manifest = GenerationManifest.model_validate_json(
            manifest_file.read_text(encoding="utf-8")
        )
        allowed_paths = set(manifest.artifact_hashes.keys()) | {"manifest.json"}
        actual_paths = {
            p.relative_to(package_dir).as_posix() for p in all_files
        }
        unmanifested = sorted(actual_paths - allowed_paths)
        if unmanifested:
            raise ValueError(
                f"Refusing to export ZIP containing unmanifested files: {unmanifested}"
            )
        missing = sorted(set(manifest.artifact_hashes.keys()) - actual_paths)
        if missing:
            raise ValueError(
                f"Refusing to export ZIP missing manifested files: {missing}"
            )
        for rel_posix, expected_sha in manifest.artifact_hashes.items():
            actual_sha = sha256_hex((package_dir / rel_posix).read_bytes())
            if actual_sha != expected_sha:
                raise ValueError(
                    f"Refusing to export ZIP: hash mismatch for '{rel_posix}'"
                )

    with zipfile.ZipFile(zip_path, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for file_path in all_files:
            rel_posix = file_path.relative_to(package_dir).as_posix()
            info = zipfile.ZipInfo(filename=rel_posix, date_time=FIXED_ZIP_DATETIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.create_system = 3  # Unix attribute format for cross-OS determinism
            info.external_attr = (0o100644 & 0xFFFF) << 16
            zf.writestr(info, file_path.read_bytes())

    return zip_path.read_bytes()
